### ISSUE TITLE
PEP8 report for PR

### ISSUE THREAD

**Issue by greut** [inveniosoftware-attic/kwalitee#1]
Kwalitee doesn't run `pep8`/`flake8`/`frosted` tests upon pull requests.
- [x] [fork it](https://github.com/greut/invenio-kwalitee) and [get it running](http://kwalitee.whut.ch/)
- [x] pep8 / flake8 kwalitee
- [x] write basic [integration](http://flask.pocoo.org/docs/testing/) [tests](https://pythonhosted.org/Flask-Testing/) (~~#3~~, ~~#5~~)
- [x] make checks asynchronous to avoid timeout from github (~~#7~~)
- [x] add pep8 support for the pull request event (~~#8~~)
- [x] add pyflakes support (~~#10~~, ~~#11~~)
- [x] Python 2.6 support (~~#12~~)
- [x] add license checks for python (+jinja) (~~#4~~, ~~#13~~)

The idea is to collect all the files modified during the pull request, grab the latest version of them, run `flake8` on them and post a comment on the latest commit. So doing a `pull -f` on the branch will clean up any previous reports.
